# Generated by Django 4.0 on 2025-04-21 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(unique=True)),
                ('grid_type', models.CharField(choices=[('REAL_TIME', 'Real-time'), ('ULTRA_CONCURRENT', 'UltraConcurrent')], default='REAL_TIME', max_length=20)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uc_pwm', models.FloatField(blank=True, null=True)),
                ('uc_height', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('DC', 'Direct Current'), ('AC', 'Alternating Current'), ('AC_INV', 'Alternating Current with Inverter')], max_length=10)),
                ('pwm', models.FloatField(default=0.0)),
                ('time_interval', models.FloatField(default=0.0)),
                ('dc_voltage', models.FloatField(blank=True, default=0.0, null=True)),
                ('dc_current', models.FloatField(blank=True, default=0.0, null=True)),
                ('dc_power', models.FloatField(blank=True, default=0.0, null=True)),
                ('dc_energy_consumption', models.FloatField(blank=True, default=0.0, null=True)),
                ('dc_energy_charge', models.FloatField(blank=True, default=0.0, null=True)),
                ('dc_level', models.FloatField(blank=True, default=0.0, null=True)),
                ('ac_voltage', models.FloatField(blank=True, default=0.0, null=True)),
                ('ac_current', models.FloatField(blank=True, default=0.0, null=True)),
                ('ac_power', models.FloatField(blank=True, default=0.0, null=True)),
                ('ac_energy', models.FloatField(blank=True, default=0.0, null=True)),
                ('ac_frequency', models.FloatField(blank=True, default=0.0, null=True)),
                ('ac_factor', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('light', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='light_robot', to='sl.light')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_pos', models.IntegerField(default=0)),
                ('y_pos', models.IntegerField(default=0)),
                ('intensity', models.FloatField(default=0.0)),
                ('is_last', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grid_messages', to='sl.grid')),
            ],
        ),
        migrations.AddField(
            model_name='grid',
            name='light',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sl.light'),
        ),
        migrations.AddIndex(
            model_name='grid',
            index=models.Index(fields=['grid_type'], name='sl_grid_grid_ty_dd8ff6_idx'),
        ),
        migrations.AddIndex(
            model_name='grid',
            index=models.Index(fields=['uc_pwm', 'uc_height'], name='sl_grid_uc_pwm_d6cf06_idx'),
        ),
    ]
