# Generated by Django 4.0 on 2024-07-05 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("street_light_rl", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="experiment",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner_experiments",
                to="users.user",
            ),
        ),
        migrations.AddField(
            model_name="experiment",
            name="robot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="robot_experiments",
                to="street_light_rl.robot",
            ),
        ),
    ]
