# Generated by Django 4.0 on 2024-07-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('street_light_rl', '0003_remove_message_experiment_remove_message_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grid',
            name='grid_num',
            field=models.IntegerField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
