# Generated by Django 4.0 on 2024-07-30 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('street_light_rl', '0005_alter_grid_grid_message_alter_grid_grid_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grid',
            name='grid_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='street_light_rl.message'),
        ),
    ]
