# Generated by Django 4.0 on 2024-07-30 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('street_light_rl', '0006_alter_grid_grid_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grid',
            old_name='grid_num',
            new_name='grid_number',
        ),
        migrations.RemoveField(
            model_name='grid',
            name='grid_message',
        ),
        migrations.AddField(
            model_name='grid',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grid_experiment', to='street_light_rl.experiment'),
        ),
        migrations.AddField(
            model_name='message',
            name='grid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grid_messages', to='street_light_rl.grid'),
        ),
        migrations.AlterField(
            model_name='grid',
            name='robot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grid_robot', to='street_light_rl.robot'),
        ),
    ]
