# Generated by Django 4.0 on 2024-07-30 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('street_light_rl', '0008_alter_grid_experiment_alter_message_grid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grid',
            name='grid_number',
        ),
        migrations.AddField(
            model_name='grid',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='grid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grid_messages', to='street_light_rl.grid'),
        ),
    ]
