# Generated by Django 4.0 on 2024-08-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('street_light_rl', '0010_grid_height_grid_width_alter_grid_experiment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grid',
            name='height',
            field=models.IntegerField(verbose_name=True),
        ),
        migrations.AlterField(
            model_name='grid',
            name='width',
            field=models.IntegerField(verbose_name=True),
        ),
    ]
