# Generated by Django 4.0 on 2024-08-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('street_light_rl', '0011_alter_grid_height_alter_grid_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grid',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grid',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
