version: "3"

services:
  db:
    image: postgres:15-alpine
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: ${RESTART_POLICY}
  app:
    build:
      context: .
    ports:
      - "8001:8000"
    volumes:
      - ./app:/app
    env_file: .env
    depends_on:
      - db
    restart: ${RESTART_POLICY}
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  postgres_data:
  redis_data:
